### ISSUE TITLE
name 'selective_scan_cuda_core' is not defined

### ISSUE THREAD

**Issue by FayeLyj** [HZAI-ZJNU/Mamba-YOLO#22]
When I run the code I get the following error

I successfully installed mamba-ssm and selective_scan ,my torch and cuda is 2.3.1 and 12.1

(yolo) root@DESKTOP-7A5MO96:/home/meti/yolo/Mamba-YOLO-main# python3 mbyolo_train.py
No module named 'selective_scan_cuda_core'
WARNING ⚠️ no model scale passed. Assuming scale='T'.
Traceback (most recent call last):
  File "mbyolo_train.py", line 44, in <module>
    "train": YOLO(model_conf).train(**args),
  File "/home/meti/yolo/Mamba-YOLO-main/ultralytics/models/yolo/model.py", line 23, in __init__
    super().__init__(model=model, task=task, verbose=verbose)
  File "/home/meti/yolo/Mamba-YOLO-main/ultralytics/engine/model.py", line 150, in __init__
    self._new(model, task=task, verbose=verbose)
  File "/home/meti/yolo/Mamba-YOLO-main/ultralytics/engine/model.py", line 219, in _new
    self.model = (model or self._smart_load("model"))(cfg_dict, verbose=verbose and RANK == -1)  # build model
  File "/home/meti/yolo/Mamba-YOLO-main/ultralytics/nn/tasks.py", line 310, in __init__
    raise e
  File "/home/meti/yolo/Mamba-YOLO-main/ultralytics/nn/tasks.py", line 301, in __init__
    m.stride = torch.tensor([s / x.shape[-2] for x in forward(torch.zeros(1, ch, s, s))])  # forward
  File "/home/meti/yolo/Mamba-YOLO-main/ultralytics/nn/tasks.py", line 299, in <lambda>
    forward = lambda x: self.forward(x)[0] if isinstance(m, (Segment, Pose, OBB)) else self.forward(x)
  File "/home/meti/yolo/Mamba-YOLO-main/ultralytics/nn/tasks.py", line 92, in forward
    return self.predict(x, *args, **kwargs)
  File "/home/meti/yolo/Mamba-YOLO-main/ultralytics/nn/tasks.py", line 110, in predict
    return self._predict_once(x, profile, visualize, embed)
  File "/home/meti/yolo/Mamba-YOLO-main/ultralytics/nn/tasks.py", line 131, in _predict_once
    x = m(x)  # run
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/meti/yolo/Mamba-YOLO-main/ultralytics/nn/modules/mamba_yolo.py", line 382, in forward
    x = input + self.drop_path(self.op(self.norm(X1)))
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/meti/yolo/Mamba-YOLO-main/ultralytics/nn/modules/mamba_yolo.py", line 186, in forward
    y = self.forward_core(x, channel_first=(self.d_conv > 1))
  File "/home/meti/yolo/Mamba-YOLO-main/ultralytics/nn/modules/mamba_yolo.py", line 165, in forward_corev2
    x = cross_selective_scan(
  File "/home/meti/yolo/Mamba-YOLO-main/ultralytics/nn/modules/common_utils_mbyolo.py", line 192, in cross_selective_scan
    ys: torch.Tensor = selective_scan(
  File "/home/meti/yolo/Mamba-YOLO-main/ultralytics/nn/modules/common_utils_mbyolo.py", line 168, in selective_scan
    return SelectiveScan.apply(u, delta, A, B, C, D, delta_bias, delta_softplus, nrows, backnrows, ssoflex)
  File "/usr/local/lib/python3.8/dist-packages/torch/autograd/function.py", line 598, in apply
    return super().apply(*args, **kwargs)  # type: ignore[misc]
  File "/usr/local/lib/python3.8/dist-packages/torch/cuda/amp/autocast_mode.py", line 115, in decorate_fwd
    return fwd(*args, **kwargs)
  File "/home/meti/yolo/Mamba-YOLO-main/ultralytics/nn/modules/common_utils_mbyolo.py", line 125, in forward
    out, x, *rest = selective_scan_cuda_core.fwd(u, delta, A, B, C, D, delta_bias, delta_softplus, 1)
NameError: name 'selective_scan_cuda_core' is not defined

**Comment by YushengEdward** [comment]
Hello！
I‘m wondering if you have solved the problem? If you have make it, would you mind teach me how solve this troublesome problem
