### ISSUE TITLE
Pip install. Error, can you help me solve it?

### ISSUE THREAD

**Issue by dyzlumos** [HZAI-ZJNU/Mamba-YOLO#31]
Processing /data/dyz/Mamba-YOLO-main/selective_scan
  Preparing metadata (setup.py) ... done
Requirement already satisfied: torch in /home/anaconda3/envs/mambayolo1/lib/python3.8/site-packages (from selective_scan==0.0.2) (2.3.0)
Requirement already satisfied: packaging in /home/anaconda3/envs/mambayolo1/lib/python3.8/site-packages (from selective_scan==0.0.2) (24.1)
Collecting ninja (from selective_scan==0.0.2)
  Using cached ninja-1.11.1.1-py2.py3-none-manylinux1_x86_64.manylinux_2_5_x86_64.whl.metadata (5.3 kB)
Requirement already satisfied: einops in /home/anaconda3/envs/mambayolo1/lib/python3.8/site-packages (from selective_scan==0.0.2) (0.8.0)
Requirement already satisfied: filelock in /home/anaconda3/envs/mambayolo1/lib/python3.8/site-packages (from torch->selective_scan==0.0.2) (3.15.4)
Requirement already satisfied: typing-extensions>=4.8.0 in /home/anaconda3/envs/mambayolo1/lib/python3.8/site-packages (from torch->selective_scan==0.0.2) (4.12.2)
Requirement already satisfied: sympy in /home/anaconda3/envs/mambayolo1/lib/python3.8/site-packages (from torch->selective_scan==0.0.2) (1.13.0)
Requirement already satisfied: networkx in /home/anaconda3/envs/mambayolo1/lib/python3.8/site-packages (from torch->selective_scan==0.0.2) (3.1)
Requirement already satisfied: jinja2 in /home/anaconda3/envs/mambayolo1/lib/python3.8/site-packages (from torch->selective_scan==0.0.2) (3.1.4)
Requirement already satisfied: fsspec in /home/anaconda3/envs/mambayolo1/lib/python3.8/site-packages (from torch->selective_scan==0.0.2) (2024.6.1)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.1.105 in /home/anaconda3/envs/mambayolo1/lib/python3.8/site-packages (from torch->selective_scan==0.0.2) (12.1.105)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.1.105 in /home/anaconda3/envs/mambayolo1/lib/python3.8/site-packages (from torch->selective_scan==0.0.2) (12.1.105)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.1.105 in /home/anaconda3/envs/mambayolo1/lib/python3.8/site-packages (from torch->selective_scan==0.0.2) (12.1.105)
Requirement already satisfied: nvidia-cudnn-cu12==8.9.2.26 in /home/anaconda3/envs/mambayolo1/lib/python3.8/site-packages (from torch->selective_scan==0.0.2) (8.9.2.26)
Requirement already satisfied: nvidia-cublas-cu12==12.1.3.1 in /home/anaconda3/envs/mambayolo1/lib/python3.8/site-packages (from torch->selective_scan==0.0.2) (12.1.3.1)
Requirement already satisfied: nvidia-cufft-cu12==11.0.2.54 in /home/anaconda3/envs/mambayolo1/lib/python3.8/site-packages (from torch->selective_scan==0.0.2) (11.0.2.54)
Requirement already satisfied: nvidia-curand-cu12==10.3.2.106 in /home/anaconda3/envs/mambayolo1/lib/python3.8/site-packages (from torch->selective_scan==0.0.2) (10.3.2.106)
Requirement already satisfied: nvidia-cusolver-cu12==11.4.5.107 in /home/anaconda3/envs/mambayolo1/lib/python3.8/site-packages (from torch->selective_scan==0.0.2) (11.4.5.107)
Requirement already satisfied: nvidia-cusparse-cu12==12.1.0.106 in /home/anaconda3/envs/mambayolo1/lib/python3.8/site-packages (from torch->selective_scan==0.0.2) (12.1.0.106)
Requirement already satisfied: nvidia-nccl-cu12==2.20.5 in /home/anaconda3/envs/mambayolo1/lib/python3.8/site-packages (from torch->selective_scan==0.0.2) (2.20.5)
Requirement already satisfied: nvidia-nvtx-cu12==12.1.105 in /home/anaconda3/envs/mambayolo1/lib/python3.8/site-packages (from torch->selective_scan==0.0.2) (12.1.105)
Requirement already satisfied: triton==2.3.0 in /home/anaconda3/envs/mambayolo1/lib/python3.8/site-packages (from torch->selective_scan==0.0.2) (2.3.0)
Requirement already satisfied: nvidia-nvjitlink-cu12 in /home/anaconda3/envs/mambayolo1/lib/python3.8/site-packages (from nvidia-cusolver-cu12==11.4.5.107->torch->selective_scan==0.0.2) (12.5.82)
Requirement already satisfied: MarkupSafe>=2.0 in /home/anaconda3/envs/mambayolo1/lib/python3.8/site-packages (from jinja2->torch->selective_scan==0.0.2) (2.1.5)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /home/anaconda3/envs/mambayolo1/lib/python3.8/site-packages (from sympy->torch->selective_scan==0.0.2) (1.3.0)
Using cached ninja-1.11.1.1-py2.py3-none-manylinux1_x86_64.manylinux_2_5_x86_64.whl (307 kB)
Building wheels for collected packages: selective_scan
  Building wheel for selective_scan (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [66 lines of output]
      
      
      torch.__version__  = 2.3.0+cu121
      
      
      
      
      CUDA_HOME = /usr/local/cuda
      
      
      CUDA version:  12.4
      running bdist_wheel
      /home/anaconda3/envs/mambayolo1/lib/python3.8/site-packages/torch/utils/cpp_extension.py:499: UserWarning: Attempted to use ninja as the BuildExtension backend but we could not find ninja.. Falling back to using the slow distutils backend.
        warnings.warn(msg.format('we could not find ninja.'))
      running build
      running build_ext
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/data/dyz/Mamba-YOLO-main/selective_scan/setup.py", line 148, in <module>
          setup(
        File "/home/anaconda3/envs/mambayolo1/lib/python3.8/site-packages/setuptools/__init__.py", line 104, in setup
          return distutils.core.setup(**attrs)
        File "/home/anaconda3/envs/mambayolo1/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 184, in setup
          return run_commands(dist)
        File "/home/anaconda3/envs/mambayolo1/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 200, in run_commands
          dist.run_commands()
        File "/home/anaconda3/envs/mambayolo1/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "/home/anaconda3/envs/mambayolo1/lib/python3.8/site-packages/setuptools/dist.py", line 967, in run_command
          super().run_command(command)
        File "/home/anaconda3/envs/mambayolo1/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/home/anaconda3/envs/mambayolo1/lib/python3.8/site-packages/wheel/bdist_wheel.py", line 368, in run
          self.run_command("build")
        File "/home/anaconda3/envs/mambayolo1/lib/python3.8/site-packages/setuptools/_distutils/cmd.py", line 316, in run_command
          self.distribution.run_command(command)
        File "/home/anaconda3/envs/mambayolo1/lib/python3.8/site-packages/setuptools/dist.py", line 967, in run_command
          super().run_command(command)
        File "/home/anaconda3/envs/mambayolo1/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/home/anaconda3/envs/mambayolo1/lib/python3.8/site-packages/setuptools/_distutils/command/build.py", line 132, in run
          self.run_command(cmd_name)
        File "/home/anaconda3/envs/mambayolo1/lib/python3.8/site-packages/setuptools/_distutils/cmd.py", line 316, in run_command
          self.distribution.run_command(command)
        File "/home/anaconda3/envs/mambayolo1/lib/python3.8/site-packages/setuptools/dist.py", line 967, in run_command
          super().run_command(command)
        File "/home/anaconda3/envs/mambayolo1/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/home/anaconda3/envs/mambayolo1/lib/python3.8/site-packages/setuptools/command/build_ext.py", line 91, in run
          _build_ext.run(self)
        File "/home/anaconda3/envs/mambayolo1/lib/python3.8/site-packages/setuptools/_distutils/command/build_ext.py", line 359, in run
          self.build_extensions()
        File "/home/anaconda3/envs/mambayolo1/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 508, in build_extensions
          compiler_name, compiler_version = self._check_abi()
        File "/home/anaconda3/envs/mambayolo1/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 894, in _check_abi
          _, version = get_compiler_abi_compatibility_and_version(compiler)
        File "/home/anaconda3/envs/mambayolo1/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 362, in get_compiler_abi_compatibility_and_version
          if not check_compiler_ok_for_platform(compiler):
        File "/home/anaconda3/envs/mambayolo1/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 315, in check_compiler_ok_for_platform
          which = subprocess.check_output(['which', compiler], stderr=subprocess.STDOUT)
        File "/home/anaconda3/envs/mambayolo1/lib/python3.8/subprocess.py", line 415, in check_output
          return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
        File "/home/anaconda3/envs/mambayolo1/lib/python3.8/subprocess.py", line 516, in run
          raise CalledProcessError(retcode, process.args,
      subprocess.CalledProcessError: Command '['which', 'g++']' returned non-zero exit status 1.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for selective_scan
  Running setup.py clean for selective_scan
Failed to build selective_scan
ERROR: Could not build wheels for selective_scan, which is required to install pyproject.toml-based projects

**Comment by EthanW-coder** [comment]
If you only have one GPU, set device to '0'.

**Comment by LennoxWei** [comment]
how to set device='0' in Ubuntu terminal? I put in device='0' and it still got the same error

**Comment by LennoxWei** [comment]
before:
torch.cuda.is_available(): True
torch.cuda.device_count(): 1
os.environ['CUDA_VISIBLE_DEVICES']: None

after:
torch.cuda.is_available(): True
torch.cuda.device_count(): 1
os.environ['CUDA_VISIBLE_DEVICES']: 0
