### ISSUE TITLE
 'YOLO' object has no attribute 'test'

### ISSUE THREAD

**Issue by Sine7812** [HZAI-ZJNU/Mamba-YOLO#42]
Traceback (most recent call last):
  File "/mnt/e/code/Mamba-YOLO-main/mbyolo_train.py", line 46, in <module>
    "test": YOLO(model_conf).test(**args),
            ^^^^^^^^^^^^^^^^^^^^^
  File "/home/jcz/anaconda3/envs/mambayolo/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1709, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'YOLO' object has no attribute 'test'
  Why does this problem occur?

**Comment by Laulen** [comment]
> 回溯（最近一次调用最后一次）： 文件“/mnt/e/code/Mamba-YOLO-main/mbyolo_train.py”，第 46 行，在 “test”中：YOLO(model_conf).test(**args)， ^^^^^^^^^^^^^^^^^^^^^^^ 文件“/home/jcz/anaconda3/envs/mambayolo/lib/python3.11/site-packages/torch/nn/modules/module.py”，第 1709 行，在**getattr**中 引发 AttributeError(f“'{type(self). **name** }' 对象没有属性'{name}'”） AttributeError：'YOLO' 对象没有属性'test' 为什么会出现这个问题？

I have the same problem, can you solve it? What am I supposed to do

**Comment by meteoritec** [comment]
I’ve encountered the same issue. I found this link: https://github.com/orgs/ultralytics/discussions/3461. It seems that YOLOv8 indeed does not have a dedicated method for handling the test dataset, but instead, you should treat the test dataset in a similar way to the validation dataset.

**Comment by zhang123-lf** [comment]
> 我也遇到了同样的问题。我找到了这个链接：https://github.com/orgs/ultralytics/discussions/3461。看来 YOLOv8 确实没有专门处理测试数据集的方法，但你应该以类似于验证数据集的方式处理测试数据集。 我注释掉了以下代码段，它运行正常： ` "test": YOLO(model_conf).test(**args),`

你好，请问在验证集上各项指标为0你是怎么解决的捏
