### ISSUE TITLE
cd selective_scan && pip install .    failed to build

### ISSUE THREAD

**Issue by Ronin-711** [HZAI-ZJNU/Mamba-YOLO#46]
(mambayolo) D:\Project\Mamba-YOLO\Mamba-YOLO-main\selective_scan>pip install .
Processing d:\project\mamba-yolo\mamba-yolo-main\selective_scan
  Preparing metadata (setup.py) ... done
Requirement already satisfied: torch in d:\annaconda\envs\mambayolo\lib\site-packages (from selective_scan==0.0.2) (2.3.0)
Requirement already satisfied: packaging in d:\annaconda\envs\mambayolo\lib\site-packages (from selective_scan==0.0.2) (24.1)
Collecting ninja (from selective_scan==0.0.2)
  Using cached ninja-1.11.1.1-py2.py3-none-win_amd64.whl.metadata (5.4 kB)
Requirement already satisfied: einops in d:\annaconda\envs\mambayolo\lib\site-packages (from selective_scan==0.0.2) (0.8.0)
Requirement already satisfied: filelock in d:\annaconda\envs\mambayolo\lib\site-packages (from torch->selective_scan==0.0.2) (3.13.1)
Requirement already satisfied: typing-extensions>=4.8.0 in d:\annaconda\envs\mambayolo\lib\site-packages (from torch->selective_scan==0.0.2) (4.11.0)
Requirement already satisfied: sympy in d:\annaconda\envs\mambayolo\lib\site-packages (from torch->selective_scan==0.0.2) (1.13.2)
Requirement already satisfied: networkx in d:\annaconda\envs\mambayolo\lib\site-packages (from torch->selective_scan==0.0.2) (3.3)
Requirement already satisfied: jinja2 in d:\annaconda\envs\mambayolo\lib\site-packages (from torch->selective_scan==0.0.2) (3.1.4)
Requirement already satisfied: fsspec in d:\annaconda\envs\mambayolo\lib\site-packages (from torch->selective_scan==0.0.2) (2024.9.0)
Requirement already satisfied: mkl<=2021.4.0,>=2021.1.1 in d:\annaconda\envs\mambayolo\lib\site-packages (from torch->selective_scan==0.0.2) (2021.4.0)
Requirement already satisfied: intel-openmp==2021.* in d:\annaconda\envs\mambayolo\lib\site-packages (from mkl<=2021.4.0,>=2021.1.1->torch->selective_scan==0.0.2) (2021.4.0)
Requirement already satisfied: tbb==2021.* in d:\annaconda\envs\mambayolo\lib\site-packages (from mkl<=2021.4.0,>=2021.1.1->torch->selective_scan==0.0.2) (2021.13.1)
Requirement already satisfied: MarkupSafe>=2.0 in d:\annaconda\envs\mambayolo\lib\site-packages (from jinja2->torch->selective_scan==0.0.2) (2.1.3)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in d:\annaconda\envs\mambayolo\lib\site-packages (from sympy->torch->selective_scan==0.0.2) (1.3.0)
Using cached ninja-1.11.1.1-py2.py3-none-win_amd64.whl (312 kB)
Building wheels for collected packages: selective_scan
  Building wheel for selective_scan (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [65 lines of output]

      torch.__version__  = 2.3.0

      CUDA_HOME = C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA\v12.1

      CUDA version:  12.1
      running bdist_wheel
      D:\annaconda\envs\mambayolo\Lib\site-packages\torch\utils\cpp_extension.py:499: UserWarning: Attempted to use ninja as the BuildExtension backend but we could not find ninja.. Falling back to using the slow distutils backend.
        warnings.warn(msg.format('we could not find ninja.'))
      running build
      running build_ext
      D:\annaconda\envs\mambayolo\Lib\site-packages\torch\utils\cpp_extension.py:384: UserWarning: Error checking compiler version for cl: [WinError 2] 系统找不到指定的文件。
        warnings.warn(f'Error checking compiler version for {compiler}: {error}')
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "D:\Project\Mamba-YOLO\Mamba-YOLO-main\selective_scan\setup.py", line 142, in <module>
          setup(
        File "D:\annaconda\envs\mambayolo\Lib\site-packages\setuptools\__init__.py", line 108, in setup
          return distutils.core.setup(**attrs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "D:\annaconda\envs\mambayolo\Lib\site-packages\setuptools\_distutils\core.py", line 184, in setup
          return run_commands(dist)
                 ^^^^^^^^^^^^^^^^^^
        File "D:\annaconda\envs\mambayolo\Lib\site-packages\setuptools\_distutils\core.py", line 200, in run_commands
          dist.run_commands()
        File "D:\annaconda\envs\mambayolo\Lib\site-packages\setuptools\_distutils\dist.py", line 970, in run_commands
          self.run_command(cmd)
        File "D:\annaconda\envs\mambayolo\Lib\site-packages\setuptools\dist.py", line 945, in run_command
          super().run_command(command)
        File "D:\annaconda\envs\mambayolo\Lib\site-packages\setuptools\_distutils\dist.py", line 989, in run_command
          cmd_obj.run()
        File "D:\annaconda\envs\mambayolo\Lib\site-packages\wheel\_bdist_wheel.py", line 378, in run
          self.run_command("build")
        File "D:\annaconda\envs\mambayolo\Lib\site-packages\setuptools\_distutils\cmd.py", line 316, in run_command
          self.distribution.run_command(command)
        File "D:\annaconda\envs\mambayolo\Lib\site-packages\setuptools\dist.py", line 945, in run_command
          super().run_command(command)
        File "D:\annaconda\envs\mambayolo\Lib\site-packages\setuptools\_distutils\dist.py", line 989, in run_command
          cmd_obj.run()
        File "D:\annaconda\envs\mambayolo\Lib\site-packages\setuptools\_distutils\command\build.py", line 135, in run
          self.run_command(cmd_name)
        File "D:\annaconda\envs\mambayolo\Lib\site-packages\setuptools\_distutils\cmd.py", line 316, in run_command
          self.distribution.run_command(command)
        File "D:\annaconda\envs\mambayolo\Lib\site-packages\setuptools\dist.py", line 945, in run_command
          super().run_command(command)
        File "D:\annaconda\envs\mambayolo\Lib\site-packages\setuptools\_distutils\dist.py", line 989, in run_command
          cmd_obj.run()
        File "D:\annaconda\envs\mambayolo\Lib\site-packages\setuptools\command\build_ext.py", line 93, in run
          _build_ext.run(self)
        File "D:\annaconda\envs\mambayolo\Lib\site-packages\setuptools\_distutils\command\build_ext.py", line 359, in run
          self.build_extensions()
        File "D:\annaconda\envs\mambayolo\Lib\site-packages\torch\utils\cpp_extension.py", line 522, in build_extensions
          _check_cuda_version(compiler_name, compiler_version)
        File "D:\annaconda\envs\mambayolo\Lib\site-packages\torch\utils\cpp_extension.py", line 417, in _check_cuda_version
          raise RuntimeError(CUDA_MISMATCH_MESSAGE.format(cuda_str_version, torch.version.cuda))
      RuntimeError:
      The detected CUDA version (12.1) mismatches the version that was used to compile
      PyTorch (11.8). Please make sure to use the same CUDA versions.

      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for selective_scan
  Running setup.py clean for selective_scan
Failed to build selective_scan
ERROR: ERROR: Failed to build installable wheels for some pyproject.toml based projects (selective_scan)
在进行cd selective_scan && pip install .  这一步操作后，所显示报错

**Comment by EthanW-coder** [comment]
This problem is caused by the fact that your CUDA version (12.1) does not correspond to PyTorch (11.8), so please install it accordingly.
