### ISSUE TITLE
为什么训练完一个epoch后的验证部分报错了，报错情况如下

### ISSUE THREAD

**Issue by jjxyhb** [HZAI-ZJNU/Mamba-YOLO#52]
Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 625/625 [02:22<00:00,  4.40it/s]
Traceback (most recent call last):
  File "/home/dell/CV408/hb/Mamba-YOLO/mbyolo_train.py", line 44, in <module>
    "train": YOLO(model_conf).train(**args),
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dell/CV408/hb/Mamba-YOLO/ultralytics/engine/model.py", line 674, in train
    self.trainer.train()
  File "/home/dell/CV408/hb/Mamba-YOLO/ultralytics/engine/trainer.py", line 199, in train
    self._do_train(world_size)
  File "/home/dell/CV408/hb/Mamba-YOLO/ultralytics/engine/trainer.py", line 424, in _do_train
    self.metrics, self.fitness = self.validate()
                                 ^^^^^^^^^^^^^^^
  File "/home/dell/CV408/hb/Mamba-YOLO/ultralytics/engine/trainer.py", line 565, in validate
    metrics = self.validator(self)
              ^^^^^^^^^^^^^^^^^^^^
  File "/home/dell/anaconda3/envs/mambayolo/lib/python3.11/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/dell/CV408/hb/Mamba-YOLO/ultralytics/engine/validator.py", line 195, in __call__
    stats = self.get_stats()
            ^^^^^^^^^^^^^^^^
  File "/home/dell/CV408/hb/Mamba-YOLO/ultralytics/models/yolo/detect/val.py", line 172, in get_stats
    stats = {k: torch.cat(v, 0).cpu().numpy() for k, v in self.stats.items()}  # to numpy
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dell/CV408/hb/Mamba-YOLO/ultralytics/models/yolo/detect/val.py", line 172, in <dictcomp>
    stats = {k: torch.cat(v, 0).cpu().numpy() for k, v in self.stats.items()}  # to numpy
                ^^^^^^^^^^^^^^^
RuntimeError: torch.cat(): expected a non-empty list of Tensors

**Comment by PureloveSh** [comment]
一样的问题

**Comment by sunjiahui1234** [comment]
请问你解决了吗，我也遇到了
