### ISSUE TITLE
Selective Scan error

### ISSUE THREAD

**Issue by JinsJinsAgain** [HZAI-ZJNU/Mamba-YOLO#60]
Hello, I have a question about the installation of selective scan.

I have been facing the error as follows.

Can you help me fix this problem, please?

(mamba) root@03f286ec9293:/home/ajs/Extdata/Mamba-YOLO/selective_scan# pip install .
Processing /home/ajs/Extdata/Mamba-YOLO/selective_scan
  Preparing metadata (setup.py) ... done
Requirement already satisfied: torch in /opt/conda/envs/mamba/lib/python3.11/site-packages (from selective_scan==0.0.2) (2.2.1)
Requirement already satisfied: packaging in /opt/conda/envs/mamba/lib/python3.11/site-packages (from selective_scan==0.0.2) (24.2)
Collecting ninja (from selective_scan==0.0.2)
  Using cached ninja-1.11.1.2-py3-none-manylinux_2_12_x86_64.manylinux2010_x86_64.whl.metadata (5.3 kB)
Requirement already satisfied: einops in /opt/conda/envs/mamba/lib/python3.11/site-packages (from selective_scan==0.0.2) (0.8.0)
Requirement already satisfied: filelock in /opt/conda/envs/mamba/lib/python3.11/site-packages (from torch->selective_scan==0.0.2) (3.16.1)
Requirement already satisfied: typing-extensions>=4.8.0 in /opt/conda/envs/mamba/lib/python3.11/site-packages (from torch->selective_scan==0.0.2) (4.12.2)
Requirement already satisfied: sympy in /opt/conda/envs/mamba/lib/python3.11/site-packages (from torch->selective_scan==0.0.2) (1.13.3)
Requirement already satisfied: networkx in /opt/conda/envs/mamba/lib/python3.11/site-packages (from torch->selective_scan==0.0.2) (3.4.2)
Requirement already satisfied: jinja2 in /opt/conda/envs/mamba/lib/python3.11/site-packages (from torch->selective_scan==0.0.2) (3.1.4)
Requirement already satisfied: fsspec in /opt/conda/envs/mamba/lib/python3.11/site-packages (from torch->selective_scan==0.0.2) (2024.10.0)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.1.105 in /opt/conda/envs/mamba/lib/python3.11/site-packages (from torch->selective_scan==0.0.2) (12.1.105)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.1.105 in /opt/conda/envs/mamba/lib/python3.11/site-packages (from torch->selective_scan==0.0.2) (12.1.105)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.1.105 in /opt/conda/envs/mamba/lib/python3.11/site-packages (from torch->selective_scan==0.0.2) (12.1.105)
Requirement already satisfied: nvidia-cudnn-cu12==8.9.2.26 in /opt/conda/envs/mamba/lib/python3.11/site-packages (from torch->selective_scan==0.0.2) (8.9.2.26)
Requirement already satisfied: nvidia-cublas-cu12==12.1.3.1 in /opt/conda/envs/mamba/lib/python3.11/site-packages (from torch->selective_scan==0.0.2) (12.1.3.1)
Requirement already satisfied: nvidia-cufft-cu12==11.0.2.54 in /opt/conda/envs/mamba/lib/python3.11/site-packages (from torch->selective_scan==0.0.2) (11.0.2.54)
Requirement already satisfied: nvidia-curand-cu12==10.3.2.106 in /opt/conda/envs/mamba/lib/python3.11/site-packages (from torch->selective_scan==0.0.2) (10.3.2.106)
Requirement already satisfied: nvidia-cusolver-cu12==11.4.5.107 in /opt/conda/envs/mamba/lib/python3.11/site-packages (from torch->selective_scan==0.0.2) (11.4.5.107)
Requirement already satisfied: nvidia-cusparse-cu12==12.1.0.106 in /opt/conda/envs/mamba/lib/python3.11/site-packages (from torch->selective_scan==0.0.2) (12.1.0.106)
Requirement already satisfied: nvidia-nccl-cu12==2.19.3 in /opt/conda/envs/mamba/lib/python3.11/site-packages (from torch->selective_scan==0.0.2) (2.19.3)
Requirement already satisfied: nvidia-nvtx-cu12==12.1.105 in /opt/conda/envs/mamba/lib/python3.11/site-packages (from torch->selective_scan==0.0.2) (12.1.105)
Requirement already satisfied: triton==2.2.0 in /opt/conda/envs/mamba/lib/python3.11/site-packages (from torch->selective_scan==0.0.2) (2.2.0)
Requirement already satisfied: nvidia-nvjitlink-cu12 in /opt/conda/envs/mamba/lib/python3.11/site-packages (from nvidia-cusolver-cu12==11.4.5.107->torch->selective_scan==0.0.2) (12.6.85)
Requirement already satisfied: MarkupSafe>=2.0 in /opt/conda/envs/mamba/lib/python3.11/site-packages (from jinja2->torch->selective_scan==0.0.2) (3.0.2)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /opt/conda/envs/mamba/lib/python3.11/site-packages (from sympy->torch->selective_scan==0.0.2) (1.3.0)
Using cached ninja-1.11.1.2-py3-none-manylinux_2_12_x86_64.manylinux2010_x86_64.whl (422 kB)
Building wheels for collected packages: selective_scan
  Building wheel for selective_scan (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [105 lines of output]

      torch.__version__  = 2.2.1+cu121

      CUDA_HOME = /usr/local/cuda

      CUDA version:  12.1
      running bdist_wheel
      running build
      running build_ext
      /opt/conda/envs/mamba/lib/python3.11/site-packages/torch/utils/cpp_extension.py:425: UserWarning: There are no g++ version bounds defined for CUDA version 12.1
        warnings.warn(f'There are no {compiler_name} version bounds defined for CUDA version {cuda_str_version}')
      building 'selective_scan_cuda_core' extension
      creating /home/ajs/Extdata/Mamba-YOLO/selective_scan/build/temp.linux-x86_64-cpython-311/csrc/selective_scan/cus
      Emitting ninja build file /home/ajs/Extdata/Mamba-YOLO/selective_scan/build/temp.linux-x86_64-cpython-311/build.ninja...
      Compiling objects...
      Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
      [1/3] /usr/local/cuda/bin/nvcc --generate-dependencies-with-compile --dependency-output /home/ajs/Extdata/Mamba-YOLO/selective_scan/build/temp.linux-x86_64-cpython-311/csrc/selective_scan/cus/selective_scan_core_fwd.o.d -I/home/ajs/Extdata/Mamba-YOLO/selective_scan/csrc/selective_scan -I/opt/conda/envs/mamba/lib/python3.11/site-packages/torch/include -I/opt/conda/envs/mamba/lib/python3.11/site-packages/torch/include/torch/csrc/api/include -I/opt/conda/envs/mamba/lib/python3.11/site-packages/torch/include/TH -I/opt/conda/envs/mamba/lib/python3.11/site-packages/torch/include/THC -I/usr/local/cuda/include -I/opt/conda/envs/mamba/include/python3.11 -c -c /home/ajs/Extdata/Mamba-YOLO/selective_scan/csrc/selective_scan/cus/selective_scan_core_fwd.cu -o /home/ajs/Extdata/Mamba-YOLO/selective_scan/build/temp.linux-x86_64-cpython-311/csrc/selective_scan/cus/selective_scan_core_fwd.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -O3 -std=c++17 -U__CUDA_NO_HALF_OPERATORS__ -U__CUDA_NO_HALF_CONVERSIONS__ -U__CUDA_NO_BFLOAT16_OPERATORS__ -U__CUDA_NO_BFLOAT16_CONVERSIONS__ -U__CUDA_NO_BFLOAT162_OPERATORS__ -U__CUDA_NO_BFLOAT162_CONVERSIONS__ --expt-relaxed-constexpr --expt-extended-lambda --use_fast_math --ptxas-options=-v -lineinfo -gencode arch=compute_70,code=sm_70 -gencode arch=compute_80,code=sm_80 -gencode arch=compute_90,code=sm_90 --threads 4 -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=selective_scan_cuda_core -D_GLIBCXX_USE_CXX11_ABI=0
      FAILED: /home/ajs/Extdata/Mamba-YOLO/selective_scan/build/temp.linux-x86_64-cpython-311/csrc/selective_scan/cus/selective_scan_core_fwd.o
      /usr/local/cuda/bin/nvcc --generate-dependencies-with-compile --dependency-output /home/ajs/Extdata/Mamba-YOLO/selective_scan/build/temp.linux-x86_64-cpython-311/csrc/selective_scan/cus/selective_scan_core_fwd.o.d -I/home/ajs/Extdata/Mamba-YOLO/selective_scan/csrc/selective_scan -I/opt/conda/envs/mamba/lib/python3.11/site-packages/torch/include -I/opt/conda/envs/mamba/lib/python3.11/site-packages/torch/include/torch/csrc/api/include -I/opt/conda/envs/mamba/lib/python3.11/site-packages/torch/include/TH -I/opt/conda/envs/mamba/lib/python3.11/site-packages/torch/include/THC -I/usr/local/cuda/include -I/opt/conda/envs/mamba/include/python3.11 -c -c /home/ajs/Extdata/Mamba-YOLO/selective_scan/csrc/selective_scan/cus/selective_scan_core_fwd.cu -o /home/ajs/Extdata/Mamba-YOLO/selective_scan/build/temp.linux-x86_64-cpython-311/csrc/selective_scan/cus/selective_scan_core_fwd.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -O3 -std=c++17 -U__CUDA_NO_HALF_OPERATORS__ -U__CUDA_NO_HALF_CONVERSIONS__ -U__CUDA_NO_BFLOAT16_OPERATORS__ -U__CUDA_NO_BFLOAT16_CONVERSIONS__ -U__CUDA_NO_BFLOAT162_OPERATORS__ -U__CUDA_NO_BFLOAT162_CONVERSIONS__ --expt-relaxed-constexpr --expt-extended-lambda --use_fast_math --ptxas-options=-v -lineinfo -gencode arch=compute_70,code=sm_70 -gencode arch=compute_80,code=sm_80 -gencode arch=compute_90,code=sm_90 --threads 4 -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=selective_scan_cuda_core -D_GLIBCXX_USE_CXX11_ABI=0
      /usr/include/cub/detail/device_synchronize.cuh(53): error: identifier "__cudaDeviceSynchronizeDeprecationAvoidance" is undefined
            result = __cudaDeviceSynchronizeDeprecationAvoidance();
                     ^

      1 error detected in the compilation of "/home/ajs/Extdata/Mamba-YOLO/selective_scan/csrc/selective_scan/cus/selective_scan_core_fwd.cu".
      [2/3] /usr/local/cuda/bin/nvcc --generate-dependencies-with-compile --dependency-output /home/ajs/Extdata/Mamba-YOLO/selective_scan/build/temp.linux-x86_64-cpython-311/csrc/selective_scan/cus/selective_scan_core_bwd.o.d -I/home/ajs/Extdata/Mamba-YOLO/selective_scan/csrc/selective_scan -I/opt/conda/envs/mamba/lib/python3.11/site-packages/torch/include -I/opt/conda/envs/mamba/lib/python3.11/site-packages/torch/include/torch/csrc/api/include -I/opt/conda/envs/mamba/lib/python3.11/site-packages/torch/include/TH -I/opt/conda/envs/mamba/lib/python3.11/site-packages/torch/include/THC -I/usr/local/cuda/include -I/opt/conda/envs/mamba/include/python3.11 -c -c /home/ajs/Extdata/Mamba-YOLO/selective_scan/csrc/selective_scan/cus/selective_scan_core_bwd.cu -o /home/ajs/Extdata/Mamba-YOLO/selective_scan/build/temp.linux-x86_64-cpython-311/csrc/selective_scan/cus/selective_scan_core_bwd.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -O3 -std=c++17 -U__CUDA_NO_HALF_OPERATORS__ -U__CUDA_NO_HALF_CONVERSIONS__ -U__CUDA_NO_BFLOAT16_OPERATORS__ -U__CUDA_NO_BFLOAT16_CONVERSIONS__ -U__CUDA_NO_BFLOAT162_OPERATORS__ -U__CUDA_NO_BFLOAT162_CONVERSIONS__ --expt-relaxed-constexpr --expt-extended-lambda --use_fast_math --ptxas-options=-v -lineinfo -gencode arch=compute_70,code=sm_70 -gencode arch=compute_80,code=sm_80 -gencode arch=compute_90,code=sm_90 --threads 4 -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=selective_scan_cuda_core -D_GLIBCXX_USE_CXX11_ABI=0
      FAILED: /home/ajs/Extdata/Mamba-YOLO/selective_scan/build/temp.linux-x86_64-cpython-311/csrc/selective_scan/cus/selective_scan_core_bwd.o
      /usr/local/cuda/bin/nvcc --generate-dependencies-with-compile --dependency-output /home/ajs/Extdata/Mamba-YOLO/selective_scan/build/temp.linux-x86_64-cpython-311/csrc/selective_scan/cus/selective_scan_core_bwd.o.d -I/home/ajs/Extdata/Mamba-YOLO/selective_scan/csrc/selective_scan -I/opt/conda/envs/mamba/lib/python3.11/site-packages/torch/include -I/opt/conda/envs/mamba/lib/python3.11/site-packages/torch/include/torch/csrc/api/include -I/opt/conda/envs/mamba/lib/python3.11/site-packages/torch/include/TH -I/opt/conda/envs/mamba/lib/python3.11/site-packages/torch/include/THC -I/usr/local/cuda/include -I/opt/conda/envs/mamba/include/python3.11 -c -c /home/ajs/Extdata/Mamba-YOLO/selective_scan/csrc/selective_scan/cus/selective_scan_core_bwd.cu -o /home/ajs/Extdata/Mamba-YOLO/selective_scan/build/temp.linux-x86_64-cpython-311/csrc/selective_scan/cus/selective_scan_core_bwd.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -O3 -std=c++17 -U__CUDA_NO_HALF_OPERATORS__ -U__CUDA_NO_HALF_CONVERSIONS__ -U__CUDA_NO_BFLOAT16_OPERATORS__ -U__CUDA_NO_BFLOAT16_CONVERSIONS__ -U__CUDA_NO_BFLOAT162_OPERATORS__ -U__CUDA_NO_BFLOAT162_CONVERSIONS__ --expt-relaxed-constexpr --expt-extended-lambda --use_fast_math --ptxas-options=-v -lineinfo -gencode arch=compute_70,code=sm_70 -gencode arch=compute_80,code=sm_80 -gencode arch=compute_90,code=sm_90 --threads 4 -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=selective_scan_cuda_core -D_GLIBCXX_USE_CXX11_ABI=0
      /usr/include/cub/detail/device_synchronize.cuh(53): error: identifier "__cudaDeviceSynchronizeDeprecationAvoidance" is undefined
            result = __cudaDeviceSynchronizeDeprecationAvoidance();
                     ^

      1 error detected in the compilation of "/home/ajs/Extdata/Mamba-YOLO/selective_scan/csrc/selective_scan/cus/selective_scan_core_bwd.cu".
      [3/3] g++ -MMD -MF /home/ajs/Extdata/Mamba-YOLO/selective_scan/build/temp.linux-x86_64-cpython-311/csrc/selective_scan/cus/selective_scan.o.d -pthread -B /opt/conda/envs/mamba/compiler_compat -DNDEBUG -fwrapv -O2 -Wall -fPIC -O2 -isystem /opt/conda/envs/mamba/include -fPIC -O2 -isystem /opt/conda/envs/mamba/include -fPIC -I/home/ajs/Extdata/Mamba-YOLO/selective_scan/csrc/selective_scan -I/opt/conda/envs/mamba/lib/python3.11/site-packages/torch/include -I/opt/conda/envs/mamba/lib/python3.11/site-packages/torch/include/torch/csrc/api/include -I/opt/conda/envs/mamba/lib/python3.11/site-packages/torch/include/TH -I/opt/conda/envs/mamba/lib/python3.11/site-packages/torch/include/THC -I/usr/local/cuda/include -I/opt/conda/envs/mamba/include/python3.11 -c -c /home/ajs/Extdata/Mamba-YOLO/selective_scan/csrc/selective_scan/cus/selective_scan.cpp -o /home/ajs/Extdata/Mamba-YOLO/selective_scan/build/temp.linux-x86_64-cpython-311/csrc/selective_scan/cus/selective_scan.o -O3 -std=c++17 -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=selective_scan_cuda_core -D_GLIBCXX_USE_CXX11_ABI=0
      ninja: build stopped: subcommand failed.
      Traceback (most recent call last):
        File "/opt/conda/envs/mamba/lib/python3.11/site-packages/torch/utils/cpp_extension.py", line 2096, in _run_ninja_build
          subprocess.run(
        File "/opt/conda/envs/mamba/lib/python3.11/subprocess.py", line 571, in run
          raise CalledProcessError(retcode, process.args,
      subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

      The above exception was the direct cause of the following exception:

      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/home/ajs/Extdata/Mamba-YOLO/selective_scan/setup.py", line 142, in <module>
          setup(
        File "/opt/conda/envs/mamba/lib/python3.11/site-packages/setuptools/__init__.py", line 117, in setup
          return distutils.core.setup(**attrs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/opt/conda/envs/mamba/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 183, in setup
          return run_commands(dist)
                 ^^^^^^^^^^^^^^^^^^
        File "/opt/conda/envs/mamba/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 199, in run_commands
          dist.run_commands()
        File "/opt/conda/envs/mamba/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 954, in run_commands
          self.run_command(cmd)
        File "/opt/conda/envs/mamba/lib/python3.11/site-packages/setuptools/dist.py", line 950, in run_command
          super().run_command(command)
        File "/opt/conda/envs/mamba/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 973, in run_command
          cmd_obj.run()
        File "/opt/conda/envs/mamba/lib/python3.11/site-packages/wheel/_bdist_wheel.py", line 378, in run
          self.run_command("build")
        File "/opt/conda/envs/mamba/lib/python3.11/site-packages/setuptools/_distutils/cmd.py", line 316, in run_command
          self.distribution.run_command(command)
        File "/opt/conda/envs/mamba/lib/python3.11/site-packages/setuptools/dist.py", line 950, in run_command
          super().run_command(command)
        File "/opt/conda/envs/mamba/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 973, in run_command
          cmd_obj.run()
        File "/opt/conda/envs/mamba/lib/python3.11/site-packages/setuptools/_distutils/command/build.py", line 135, in run
          self.run_command(cmd_name)
        File "/opt/conda/envs/mamba/lib/python3.11/site-packages/setuptools/_distutils/cmd.py", line 316, in run_command
          self.distribution.run_command(command)
        File "/opt/conda/envs/mamba/lib/python3.11/site-packages/setuptools/dist.py", line 950, in run_command
          super().run_command(command)
        File "/opt/conda/envs/mamba/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 973, in run_command
          cmd_obj.run()
        File "/opt/conda/envs/mamba/lib/python3.11/site-packages/setuptools/command/build_ext.py", line 98, in run
          _build_ext.run(self)
        File "/opt/conda/envs/mamba/lib/python3.11/site-packages/setuptools/_distutils/command/build_ext.py", line 359, in run
          self.build_extensions()
        File "/opt/conda/envs/mamba/lib/python3.11/site-packages/torch/utils/cpp_extension.py", line 871, in build_extensions
          build_ext.build_extensions(self)
        File "/opt/conda/envs/mamba/lib/python3.11/site-packages/setuptools/_distutils/command/build_ext.py", line 476, in build_extensions
          self._build_extensions_serial()
        File "/opt/conda/envs/mamba/lib/python3.11/site-packages/setuptools/_distutils/command/build_ext.py", line 502, in _build_extensions_serial
          self.build_extension(ext)
        File "/opt/conda/envs/mamba/lib/python3.11/site-packages/setuptools/command/build_ext.py", line 263, in build_extension
          _build_ext.build_extension(self, ext)
        File "/opt/conda/envs/mamba/lib/python3.11/site-packages/setuptools/_distutils/command/build_ext.py", line 557, in build_extension
          objects = self.compiler.compile(
                    ^^^^^^^^^^^^^^^^^^^^^^
        File "/opt/conda/envs/mamba/lib/python3.11/site-packages/torch/utils/cpp_extension.py", line 684, in unix_wrap_ninja_compile
          _write_ninja_file_and_compile_objects(
        File "/opt/conda/envs/mamba/lib/python3.11/site-packages/torch/utils/cpp_extension.py", line 1774, in _write_ninja_file_and_compile_objects
          _run_ninja_build(
        File "/opt/conda/envs/mamba/lib/python3.11/site-packages/torch/utils/cpp_extension.py", line 2112, in _run_ninja_build
          raise RuntimeError(message) from e
      RuntimeError: Error compiling objects for extension
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for selective_scan
  Running setup.py clean for selective_scan
Failed to build selective_scan
ERROR: ERROR: Failed to build installable wheels for some pyproject.toml based projects (selective_scan)

**Comment by JinsJinsAgain** [comment]
I have changed gcc, g++ versions several times, but it still shows the same error.

please help me

**Comment by EthanW-coder** [comment]
This may be a problem due to an inconsistency between the cuda version and the torch version.

**Comment by nliu-25** [comment]
cuda11.8+pytorch2.1.0+ssm1.1.1+selective(linux-wheel),this way can work!

**Comment by DawnMagnet** [comment]
https://github.com/HZAI-ZJNU/Mamba-YOLO/issues/65
